In [1]:
Table of Contents:
Basics:
    1.Single dimensional array 
    2.Multi dimensional array 
    3.Check the Dimension of the array 
    4.Create and array of zeros 
    5.Check Data Type of Array 
Arrays and Scalars:
    1.ELement wise array multiplication 
    2.Indexing and slicing of arrays 
    3.Boolean Indexing 
Array Operations
    1.Slicing multi dimensional Arrays 
    2.Square Root 
    3.Array with maximum of 2 arrays
    4.Conditional logic as Array Operators
    5.The where clause in arrays 
Basic Statistical functions
    1.Mean
    2.Sum
    3.Column means (0th dimension or axis )
Misc Array operations
    1.Sorting
    2.Unique  and other Array set operations
    3.Generate a 4 by 4  Array of random numbers following Normal distribution 

SyntaxError: invalid syntax (<ipython-input-1-5f94b89151d5>, line 1)

In [2]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4.0,5])
arr

array([1., 2., 3., 4., 5.])

In [14]:
arr_multi=np.array([[1,2,3],[4,5,6]],dtype="int16")
arr_multi

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [10]:
arr_multi.shape

(2, 3)

In [11]:
arr_multi.ndim

2

In [15]:
arr_multi.dtype

dtype('int16')

In [17]:
arr_multi.size

6

In [19]:
arr_multi.nbytes

12

In [27]:
arr = np.random.randint(100,size=(3,3))
arr1=arr*arr
arr1

array([[4096,  361, 2704],
       [   0, 9801,  169],
       [4356,    0, 4900]])

In [30]:
arr = np.random.randint(100,size=(4,4))
arr

array([[54, 76, 97,  3],
       [43, 37, 63, 91],
       [57, 26, 80, 79],
       [51, 21, 72, 60]])

In [34]:
arr2=arr[1:-1,1:-1]
arr2

array([[37, 63],
       [26, 80]])

In [38]:
arr2[:,:]=0
arr

array([[54, 76, 97,  3],
       [43,  0,  0, 91],
       [57,  0,  0, 79],
       [51, 21, 72, 60]])

In [54]:
arr_name = np.array(['ameen','raju','dileep','ameen','gupta','ras','mas'])
arr_idx=np.array([0,1,2,3,4,5,6])
arr_idx[arr_name=='ameen']

array([0, 3])

In [59]:
arr
arr1=np.where(arr==0,100,arr)
arr1

array([[ 54,  76,  97,   3],
       [ 43, 100, 100,  91],
       [ 57, 100, 100,  79],
       [ 51,  21,  72,  60]])

In [61]:
arr = np.array([1,2,3,4,5])
arr1 = np.array([[1,2],[3,4]])

In [63]:
len(arr)

5

In [65]:
len(arr1)

2

In [70]:
np.random.randint(1,10,size=(3,4))

array([[5, 8, 9, 3],
       [7, 1, 6, 1],
       [1, 4, 7, 8]])

In [71]:
arr1 = np.array([[1,2],[3,4]])
arr1

array([[1, 2],
       [3, 4]])

In [77]:
arr_rpt=np.repeat(arr1,(3,4),axis=0)
arr_rpt

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4],
       [3, 4]])